# Generated by Django 3.0.2 on 2020-06-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodNet', '0002_auto_20200613_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workout',
            field=models.CharField(choices=[('1', 'Less'), ('2', 'Medium'), ('3', 'Heavy')], max_length=1),
        ),
    ]
